# 使用java环境

FROM kmelnikov88/jre14

# 缓存目录

VOLUME tmp

# 将当前项目的jar包添加到容器中
COPY target/service-file-0.0.1-SNAPSHOT.jar /service-file.jar

EXPOSE 18082

# 当容器启动时 执行启动命令
ENTRYPOINT ["java","-jar","service-file.jar"]
