spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: service-file
  cloud:
    nacos:
      discovery:
        server-addr:  192.168.1.142:8848


server:
  port: 18082


profiles:
  active: dev

feign:
  hystrix:
    enabled: false