spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: service-file
  cloud:
    nacos:
      discovery:
        server-addr:  47.116.132.145:8848


server:
  port: 18082


profiles:
  active: dev

feign:
  hystrix:
    enabled: false