# 使用java环境


FROM  kmelnikov88/jre14

# 缓存目录

VOLUME tmp

# 将当前项目的jar包添加到容器中
COPY target/api_gateway-0.0.1-SNAPSHOT.jar /api-gateway.jar

EXPOSE 8500

# 当容器启动时 执行启动命令
ENTRYPOINT ["java","-jar","api-gateway.jar"]
